### ISSUE TITLE
vagrant-centos refactored.

### ISSUE THREAD

**Issue by noitcudni** [DemandCube/NeverwinterDP_Legacy#119]
Need to add comments and update README

**Comment by smorin** [comment]
Since this is in code review please put the link to the pull request in the ticket.

**Comment by mehikmat** [comment]
@noitcudni is this link to pull request  https://github.com/DemandCube/vagrant-centos/pull/2

**Comment by mehikmat** [comment]
@noitcudni   I have following concerns

[1] I think if anybody runs setup  without any arguments then in general USAGE should be displayed otherwise on will get following error.
$ ./setup 
HDD_SIZE : 8192
DOWNLOAD_URL : http://mirror.rackspace.com/CentOS/6.5/isos/x86_64/CentOS-6.5-x86_64-minimal.iso
NAME: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0Warning: Failed to create the file ./isos/
  0  398M    0  1076    0     0    178      0  27d 03h  0:00:06  27d 03h  4154
curl: (23) Failed writing body (0 != 1076)

2) In varsh.sh, there is no support for location of VBoxGuestAddition.iso in case of Linux

3) I am confused about ks.cfg file that is it for both 6.4 and 6.5. if yes then there are certain parameters inside this which are 6.5 specific and how these are dynamically changed for 6.4 
Example:
alias yum='yum --releasever=6.5'
DHCP_HOSTNAME=vagrant-centos65.vagrantup.com

cat <<EOM >>/etc/hosts
127.0.0.1   vagrant-centos65.vagrantup.com vagrant-centos65
::1         vagrant-centos65.vagrantup.com vagrant-centos65
EOM

**Comment by smorin** [comment]
The current repo is tested and updated.  If you see those two problems then please submit a pull request
