### ISSUE TITLE
[DemandCubePlaybooks] Remove common role dependencies in gradle role

### ISSUE THREAD

**Issue by jeroldleslie** [DemandCube/NeverwinterDP_Legacy#247]
Since common role is called in main.yml at first execution, it is not necessary to have common role dependencies in gradle role. So remove it

**Comment by anthonyms** [comment]
For a simple jenkins install only main.yml is not run.  
However jenkins and gradle need some elements of commons in order to run.

Our options are
1. Leave jenkins include gradle.
2. Remove the common dependency in gradle
2. Place a comment in gradle tasks/main.yml that user should first run the common role.
3. Include the common role in jenkins_localhost.yml. 

Since main.yml is the main way of running the roles in DemandCubePlaybooks it will be left working fine.

**Comment by anthonyms** [comment]
A better way would be 
1. Let not gradle include common.
2. In gradle/tasks/main.yml only include the common elements needed (zip and unzip)

Thus gradle role will run well regardless of the way it was called.

**Comment by anthonyms** [comment]
PR addressing the second way is at https://github.com/DemandCube/DemandCubePlaybooks/pull/16
Note the jenkins role sets the precedent in pulling in only what it needs.

> jenkins/tasks/main.yml
> 
> ```
> - include: ../../../programs/git-daemon.yml
> - include: ../../../programs/sshpass.yml
> ```

**Comment by KingOfPoptart** [comment]
@artfullyContrived I think your second choice would be best.  Go ahead and remove the dependency to common and specifically call the install for zip and unzip directly since those are lightweight to install/check if they're installed in ansible.
