### ISSUE TITLE
Add groups config to vagrant-centos-template

### ISSUE THREAD

**Issue by smorin** [DemandCube/NeverwinterDP_Legacy#28]

**Comment by KingOfPoptart** [comment]
As per our discussion, since we're planning on moving the group config out of the VAGRANTFILE, is this still a valid issue?

**Comment by smorin** [comment]
Since you already wrote the functionality.  I saw no reason to remove it.
 Figure that it can try and do both.  Thoughts?

On Mon, Mar 10, 2014 at 10:35 AM, Richard Duarte
notifications@github.comwrote:

> As per our discussion, since we're planning on moving the group config out
> of the VAGRANTFILE, is this still a valid issue?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/DemandCube/NeverwinterDP/issues/28#issuecomment-37210485
> .

## 

Steve Morin | Hacker, Entrepreneur, Startup Advisor
twitter.com/SteveMorin | stevemorin.com
_Live the dream start a startup. Make the world ... a better place._

**Comment by KingOfPoptart** [comment]
Since the point of the vagrant-centos-template is to bring up a clean VM as a starting point, I don't think we should start including things that have to do with ansible configuration.  

Since our goal is to decouple the configs as much as possible I would say close this issue and don't do it.  Another reason to not include this is since we're going to move to a config-file driven system of ansible groups, this again becomes a moot point.  

I would say mark this as "will not fix" and close the issue.

**Comment by smorin** [comment]
That sounds good to me.  Rolling new ideas into https://github.com/DemandCube/NeverwinterDP/issues/29
