### ISSUE TITLE
Add gradle step to create javadoc comments for all Java code during build

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#289]
Not a high priority, but this will definitely help the team dive into working on your code.

**Comment by tuan08** [comment]
Hi ,

Due to the amount of work and the dynamic change, I won't document my code unless it is stable or there is requirement for a large number of developers. I will only document the architecture. On the other hand, I write a lot of sample code and unit test, you need to learn how to read the code and follow the unit test. 

If you do not find the unit test or sample code that you need , you can ask me and I will write the unit test for you.

**Comment by smorin** [comment]
Still try to add comments where possible to the purpose of a class

**Comment by smorin** [comment]
I finish adding this to each project

**Comment by smorin** [comment]
Sorry misread, thought was to just generate javadoc

**Comment by KingOfPoptart** [comment]
@tuan08 like we discussed yesterday you need to document your own code.

If you just add something that describes the purpose of each class you write, that will be a big help.  Commenting is part of development, its the developer's own responsibility.
