### ISSUE TITLE
[KafkaSpinner] Unit Testing for Kafka Spinner

### ISSUE THREAD

**Issue by KingOfPoptart** [DemandCube/NeverwinterDP_Legacy#440]
Create unit tests for Kafka Spinner.

This will prove that Kafka Spinner is working as expected.  Be able to parse the logs of all the Kafka machines and Zookeeper to prove that:
1. There are no unexpected errors in Zookeeper or Kafka
2. Kafka nodes are coming up and going down exactly as expected

There will be multiple tests for different configurations of KafkaSpinner.

**Comment by tuan08** [comment]
Hi,
1. You will encounter a lot of exception in the log file, some are correct behavior.  Some need to be analyzed and understand.
2. Need a way to check and prove that your kafka , zookeeper node are shutdown are launched properly. This is a repeated task and a wrong configuration  can cause problem. The common scenario you can encounter:
3. The kafka node and zookeeper node are not killed. The node take more time to be killed or  exit than the amount of time you allocate to it. It will happen when you run the real performance test and all the resource are busy and take more time to process. The best way is to design from the beginning a polling method with time out to make sure your resource are released or terminated.
4. You can start a kafka node, zookeeper node but what if the kafka broker cannot join the cluster due to the unknown problem, wrong configuration, exception...
5. If you just want to proved that the node are launched are killed, the shell script can do the work. But if you want to make sure that zookeeper or kafka are launched and connected properly , you have to either use kafka api to check or grep the kafka or zookeeper log. Use kafka api is a more powerful wait , but need more works.
6.  If you do not think or take seriously about the goal of test, a simple black box test requirement such: Write a test that send the 10 messages every second to kafka for 30 min. Make sure you don't loose any messages will block you forever. Also  you should think about the final goal of the work or the product. If you just focus on launching and killing the node and Anthony  just focus on the sending and receiving the messages. Then who will be responsible to integrate your work and Anthony work. So I think both of you need to discuss. You should think about the final goal of the work, start with the work that you do not know and have no idea how to make it and do the research for it.

**Comment by KingOfPoptart** [comment]
@tuan08 I'm not sure I follow what you mean by point 3 - Do you mean its possible shutting down a Kafka or ZK node will take longer than expected and the test needs to account for that?

**Comment by tuan08** [comment]
For example , when you shutdown a server , it will take 30s to shutdown properly due to the busy.  And you try to start it after 15s , if you do not check
