### ISSUE TITLE
Refactor KafkaProducer

### ISSUE THREAD

**Issue by tuan08** [DemandCube/NeverwinterDP_Legacy#475]
1. Create KafkaProducer in Scribengin/V2, make it depends on the server project to reuse the embedded zookeeper and kafka. You can add features to server project for your need. But make sure that I am aware about it
2. Make a test for those properties message.send.max.retries, retry.backoff.ms  to show it weakness and identify the problem.
3. If we cannot use 2, move the retry from old kafka producer with the buffer implementation

**Comment by anthonyms** [comment]
@tuan08 Please provide more info about the buffer implementation.

I am thinking of using https://github.com/DemandCube/KafkaProducer/blob/fixedSizeList/src/main/java/com/neverwinterdp/kafkaproducer/util/FixedSizeList.java

You have to understand the idea how an asynchronous buffer work and the reason to have a buffer. Basically the idea are:
1. The io operation is expensive, so to improve the performance. The buffer is used to batch the multiple io operation into one.
2. The buffer is flushed when it is full or a period of time is expired
3. You have at least 2 thread involved. One thread(or more) queue the message , one sender thread that send the messages when the buffer is full or timeout. 
4. The enqueue thread need to be blocked when the buffer is full or the sender thread dequeue.
5. The sender thread should notify  when it dequeue and invoke the callback when it deliver the messages to the remote server. The callback thread can be the same sender thread or another thread depends on the design

Before making this type of buffer,  you have to be able to make a demo program that show how use and master the synchronized keywork , the wait and notify method.

You also need to understand how kafka buffer work, the timeout configuration and setting since your message is end up in a kafka asynchronous buffer too.

**Comment by tuan08** [comment]
Write the test first and I need to look at your test first

**Comment by anthonyms** [comment]
@tuan08 
As I move the Writer to Scribenging here are a few design decisions that need your input.
- Kafka has an inbuilt TestServer and EmbededZookeeper Server. I recommend we use those. 

The reason I create the embedded server is because I want to control the number number of zookeeper and kafka instances. You can randomly shutdown the zookeeper and kafka instances for the stability test. It is not a perfect solution, but it allow you to develop and test the integration tool before you run it in real system such docker.
- KafkaWriter to at least implement Runnable.

You can create a Runnable object that use the KafkaWriter. If you implement Runnable for KafkaWriter and the writer has the problem like connection, how do you handle the error.
- 1 Constructor that takes a ZKUrl and another that takes a list of KafkaBrokers

OK
- A writer is instantiated with the topic it will write to. I see the writer you have doesn't have this. It takes a a topic at the point of writing.

A writer can write to one or multiple topic which allow you to reuse the connection and save the resource. You can create another object that reuse the writer with a single topic, like the Runnable case.
- Optionally construct the writer with a Properties file that has the necesary properties.

Usually , you can have an util or other tool class for this job.
- Use the Producer in 0.8.2

I already upgrade to use 0.8.2 and  new kafka producer api
- No need for Callback. At least not now.
- A MessageGenerator as a source of messages for the writer. Also servers as a queue where source of messages places messages for the writer.

Team can also chime in with sugestions.
Am also spending time writing the tests you requested in the previous comment.

**Comment by anthonyms** [comment]
@Tuan
With the test harness from Kafka You can start as many Kafka's and Zookeepers as you want. 
Kafka's has the advantage of properly picking an unused port for use for both the Kafka and Zookeeper servers.
